const products = [
  {
    _id: "1",
    name: "Nike Slim Shirts",
    category: "Shirts",
    image: "/images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 3.5,
    numReviews: 10,
    description: "High quality product",
  },
  {
    _id: "2",
    name: "Adida Fit Shirts",
    category: "Shirts",
    image: "/images/p2.jpg",
    price: 120,
    countInStock: 20,
    brand: "Adidas",
    rating: 3,
    numReviews: 10,
    description: "Not good",
  },
  {
    _id: "3",
    name: "Lacouste Free Shirts",
    category: "Shirts",
    image: "/images/p3.jpg",
    price: 120,
    countInStock: 5,
    brand: "Lacouste",
    rating: 4.5,
    numReviews: 15,
    description: "Overall good",
  },
  {
    _id: "4",
    name: "Nike Slim Pant",
    category: "Pants",
    image: "/images/p4.jpg",
    price: 78,
    countInStock: 0,
    brand: "Nike",
    rating: 2,
    numReviews: 15,
    description: "High quality product",
  },
  {
    _id: "5",
    name: "Adidas Fit Pant",
    category: "Shirts",
    image: "/images/p5.jpg",
    price: 100,
    countInStock: 10,
    brand: "Adidas",
    rating: 4.5,
    numReviews: 10,
    description: "High quality product",
  },
  {
    _id: "6",
    name: "Adidas Fit Pant",
    category: "Shirts",
    image: "/images/p6.jpg",
    price: 100,
    countInStock: 0,
    brand: "Adidas",
    rating: 5,
    numReviews: 10,
    description: "High quality product",
  },
];

export default products;
